/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FabButton {
        /**
          * Additional classes to add to the button
          * @default ''
         */
        "class": string;
        /**
          * Disables the button if true
          * @default false
         */
        "disabled": boolean;
        /**
          * The button sizes
          * @default 'size-default' Options are 'size-default', 'sm', 'lg', and 'icon' (for icon-only buttons)
         */
        "size": 'size-default' | 'sm' | 'lg' | 'icon';
        /**
          * The button type
          * @default 'button' Options are 'button', 'submit', and 'reset'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * The button variants
          * @default 'default' Options are 'default', 'destructive', 'outline', 'secondary', 'ghost', and 'link'
         */
        "variant": 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';
    }
    interface FabColourPalettes {
    }
    interface FabIcon {
        /**
          * Custom CSS classes to apply to the icon wrapper.
         */
        "class"?: string;
        /**
          * The fill color for the SVG. For duotone icons, this will be the primary color.
         */
        "fill"?: string;
        /**
          * The secondary fill color for duotone icons.
         */
        "fillSecondary"?: string;
        /**
          * The name of the icon to display. This should correspond to an SVG file in the assets directory (without the .svg extension).
         */
        "icon": string;
        /**
          * The size of the icon in pixels. Defaults to 16.
          * @default 16
         */
        "size": number;
        /**
          * The stroke color for the SVG.
          * @default 'var(--primary-colour, currentColor)'
         */
        "stroke"?: string;
        /**
          * The variant of the icon. Defaults to 'line'.
          * @default 'duotone'
         */
        "variant": 'solid' | 'duotone' | 'line';
    }
    interface FabOption {
        /**
          * Description text for the option (for enhanced accessibility)
         */
        "description": string;
        /**
          * Whether the option is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Optional icon class
         */
        "icon": string;
        /**
          * Optional image URL for the option
         */
        "imageUrl": string;
        /**
          * Whether the option is selected
          * @default false
         */
        "selected": boolean;
        /**
          * The option value
          * @default ''
         */
        "value": string;
    }
    interface FabPalette {
        /**
          * The base colour value (for dynamic generation). Default is 'var(--primary-colour)'.
          * @default 'var(--primary-colour)'
         */
        "colourValue": string;
    }
    interface FabSelect {
        /**
          * If multiple, how many options will be shown in the collapsed state before showing "+X more"
          * @default 2
         */
        "collapsedCount": number;
        /**
          * Whether the select is disabled
          * @default false
         */
        "disabled": boolean;
        "getValue": () => Promise<string | string[]>;
        /**
          * Whether multiple options can be selected
          * @default false
         */
        "multiple": boolean;
        /**
          * The name of the form control (used for form submission)
          * @default ''
         */
        "name": string;
        /**
          * Placeholder text to display when no option is selected
          * @default 'Select an option'
         */
        "placeholder": string;
        /**
          * Whether the select is required
          * @default false
         */
        "required": boolean;
        "setValue": (value: string | string[]) => Promise<void>;
    }
    interface FabSidebar {
    }
    interface FabSidebarContent {
    }
    interface FabSidebarFooter {
    }
    interface FabSidebarGroup {
        /**
          * Whether the group is currently collapsed.
          * @default true
         */
        "groupCollapsed"?: boolean;
        /**
          * Whether the group is collapsible.
          * @default false
         */
        "groupCollapsible"?: boolean;
        /**
          * Optional heading for the group.
         */
        "heading"?: string;
    }
    interface FabSidebarHeader {
    }
    interface FabSidebarItem {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "href": string;
        "icon": string;
        "label": string;
    }
    interface FabSitePalette {
        /**
          * The base colour value (for dynamic generation). Default is 'var(--primary-colour)'.
          * @default 'var(--primary-colour)'
         */
        "colourValue": string;
        /**
          * The colour harmony to display. Options are 'complementary', 'analogous', 'triadic', 'tetradic', 'split', and 'neutral'. Default is 'complementary'.
          * @default 'complementary'
         */
        "harmony": 'complementary' | 'analogous' | 'triadic' | 'tetradic' | 'split' | 'neutral';
        /**
          * @default true
         */
        "showHarmonies": boolean;
    }
    interface FabSkeuSwitch {
    }
    interface FabThemeSwitcher {
    }
    interface FabToggle {
        /**
          * Whether we show the indicator light
         */
        "showIndicator": boolean;
    }
    interface FabWcagPalette {
    }
}
export interface FabButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFabButtonElement;
}
export interface FabOptionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFabOptionElement;
}
export interface FabSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFabSelectElement;
}
declare global {
    interface HTMLFabButtonElementEventMap {
        "fabClick": MouseEvent;
    }
    interface HTMLFabButtonElement extends Components.FabButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFabButtonElementEventMap>(type: K, listener: (this: HTMLFabButtonElement, ev: FabButtonCustomEvent<HTMLFabButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFabButtonElementEventMap>(type: K, listener: (this: HTMLFabButtonElement, ev: FabButtonCustomEvent<HTMLFabButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFabButtonElement: {
        prototype: HTMLFabButtonElement;
        new (): HTMLFabButtonElement;
    };
    interface HTMLFabColourPalettesElement extends Components.FabColourPalettes, HTMLStencilElement {
    }
    var HTMLFabColourPalettesElement: {
        prototype: HTMLFabColourPalettesElement;
        new (): HTMLFabColourPalettesElement;
    };
    interface HTMLFabIconElement extends Components.FabIcon, HTMLStencilElement {
    }
    var HTMLFabIconElement: {
        prototype: HTMLFabIconElement;
        new (): HTMLFabIconElement;
    };
    interface HTMLFabOptionElementEventMap {
        "fabOptionSelect": string;
    }
    interface HTMLFabOptionElement extends Components.FabOption, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFabOptionElementEventMap>(type: K, listener: (this: HTMLFabOptionElement, ev: FabOptionCustomEvent<HTMLFabOptionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFabOptionElementEventMap>(type: K, listener: (this: HTMLFabOptionElement, ev: FabOptionCustomEvent<HTMLFabOptionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFabOptionElement: {
        prototype: HTMLFabOptionElement;
        new (): HTMLFabOptionElement;
    };
    interface HTMLFabPaletteElement extends Components.FabPalette, HTMLStencilElement {
    }
    var HTMLFabPaletteElement: {
        prototype: HTMLFabPaletteElement;
        new (): HTMLFabPaletteElement;
    };
    interface HTMLFabSelectElementEventMap {
        "fabChange": string | string[];
    }
    interface HTMLFabSelectElement extends Components.FabSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFabSelectElementEventMap>(type: K, listener: (this: HTMLFabSelectElement, ev: FabSelectCustomEvent<HTMLFabSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFabSelectElementEventMap>(type: K, listener: (this: HTMLFabSelectElement, ev: FabSelectCustomEvent<HTMLFabSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFabSelectElement: {
        prototype: HTMLFabSelectElement;
        new (): HTMLFabSelectElement;
    };
    interface HTMLFabSidebarElement extends Components.FabSidebar, HTMLStencilElement {
    }
    var HTMLFabSidebarElement: {
        prototype: HTMLFabSidebarElement;
        new (): HTMLFabSidebarElement;
    };
    interface HTMLFabSidebarContentElement extends Components.FabSidebarContent, HTMLStencilElement {
    }
    var HTMLFabSidebarContentElement: {
        prototype: HTMLFabSidebarContentElement;
        new (): HTMLFabSidebarContentElement;
    };
    interface HTMLFabSidebarFooterElement extends Components.FabSidebarFooter, HTMLStencilElement {
    }
    var HTMLFabSidebarFooterElement: {
        prototype: HTMLFabSidebarFooterElement;
        new (): HTMLFabSidebarFooterElement;
    };
    interface HTMLFabSidebarGroupElement extends Components.FabSidebarGroup, HTMLStencilElement {
    }
    var HTMLFabSidebarGroupElement: {
        prototype: HTMLFabSidebarGroupElement;
        new (): HTMLFabSidebarGroupElement;
    };
    interface HTMLFabSidebarHeaderElement extends Components.FabSidebarHeader, HTMLStencilElement {
    }
    var HTMLFabSidebarHeaderElement: {
        prototype: HTMLFabSidebarHeaderElement;
        new (): HTMLFabSidebarHeaderElement;
    };
    interface HTMLFabSidebarItemElement extends Components.FabSidebarItem, HTMLStencilElement {
    }
    var HTMLFabSidebarItemElement: {
        prototype: HTMLFabSidebarItemElement;
        new (): HTMLFabSidebarItemElement;
    };
    interface HTMLFabSitePaletteElement extends Components.FabSitePalette, HTMLStencilElement {
    }
    var HTMLFabSitePaletteElement: {
        prototype: HTMLFabSitePaletteElement;
        new (): HTMLFabSitePaletteElement;
    };
    interface HTMLFabSkeuSwitchElement extends Components.FabSkeuSwitch, HTMLStencilElement {
    }
    var HTMLFabSkeuSwitchElement: {
        prototype: HTMLFabSkeuSwitchElement;
        new (): HTMLFabSkeuSwitchElement;
    };
    interface HTMLFabThemeSwitcherElement extends Components.FabThemeSwitcher, HTMLStencilElement {
    }
    var HTMLFabThemeSwitcherElement: {
        prototype: HTMLFabThemeSwitcherElement;
        new (): HTMLFabThemeSwitcherElement;
    };
    interface HTMLFabToggleElement extends Components.FabToggle, HTMLStencilElement {
    }
    var HTMLFabToggleElement: {
        prototype: HTMLFabToggleElement;
        new (): HTMLFabToggleElement;
    };
    interface HTMLFabWcagPaletteElement extends Components.FabWcagPalette, HTMLStencilElement {
    }
    var HTMLFabWcagPaletteElement: {
        prototype: HTMLFabWcagPaletteElement;
        new (): HTMLFabWcagPaletteElement;
    };
    interface HTMLElementTagNameMap {
        "fab-button": HTMLFabButtonElement;
        "fab-colour-palettes": HTMLFabColourPalettesElement;
        "fab-icon": HTMLFabIconElement;
        "fab-option": HTMLFabOptionElement;
        "fab-palette": HTMLFabPaletteElement;
        "fab-select": HTMLFabSelectElement;
        "fab-sidebar": HTMLFabSidebarElement;
        "fab-sidebar-content": HTMLFabSidebarContentElement;
        "fab-sidebar-footer": HTMLFabSidebarFooterElement;
        "fab-sidebar-group": HTMLFabSidebarGroupElement;
        "fab-sidebar-header": HTMLFabSidebarHeaderElement;
        "fab-sidebar-item": HTMLFabSidebarItemElement;
        "fab-site-palette": HTMLFabSitePaletteElement;
        "fab-skeu-switch": HTMLFabSkeuSwitchElement;
        "fab-theme-switcher": HTMLFabThemeSwitcherElement;
        "fab-toggle": HTMLFabToggleElement;
        "fab-wcag-palette": HTMLFabWcagPaletteElement;
    }
}
declare namespace LocalJSX {
    interface FabButton {
        /**
          * Additional classes to add to the button
          * @default ''
         */
        "class"?: string;
        /**
          * Disables the button if true
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Emitted when the button is clicked
          * @event fabClick
         */
        "onFabClick"?: (event: FabButtonCustomEvent<MouseEvent>) => void;
        /**
          * The button sizes
          * @default 'size-default' Options are 'size-default', 'sm', 'lg', and 'icon' (for icon-only buttons)
         */
        "size"?: 'size-default' | 'sm' | 'lg' | 'icon';
        /**
          * The button type
          * @default 'button' Options are 'button', 'submit', and 'reset'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * The button variants
          * @default 'default' Options are 'default', 'destructive', 'outline', 'secondary', 'ghost', and 'link'
         */
        "variant"?: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';
    }
    interface FabColourPalettes {
    }
    interface FabIcon {
        /**
          * Custom CSS classes to apply to the icon wrapper.
         */
        "class"?: string;
        /**
          * The fill color for the SVG. For duotone icons, this will be the primary color.
         */
        "fill"?: string;
        /**
          * The secondary fill color for duotone icons.
         */
        "fillSecondary"?: string;
        /**
          * The name of the icon to display. This should correspond to an SVG file in the assets directory (without the .svg extension).
         */
        "icon"?: string;
        /**
          * The size of the icon in pixels. Defaults to 16.
          * @default 16
         */
        "size"?: number;
        /**
          * The stroke color for the SVG.
          * @default 'var(--primary-colour, currentColor)'
         */
        "stroke"?: string;
        /**
          * The variant of the icon. Defaults to 'line'.
          * @default 'duotone'
         */
        "variant"?: 'solid' | 'duotone' | 'line';
    }
    interface FabOption {
        /**
          * Description text for the option (for enhanced accessibility)
         */
        "description"?: string;
        /**
          * Whether the option is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Optional icon class
         */
        "icon"?: string;
        /**
          * Optional image URL for the option
         */
        "imageUrl"?: string;
        /**
          * Emitted when option is selected
         */
        "onFabOptionSelect"?: (event: FabOptionCustomEvent<string>) => void;
        /**
          * Whether the option is selected
          * @default false
         */
        "selected"?: boolean;
        /**
          * The option value
          * @default ''
         */
        "value"?: string;
    }
    interface FabPalette {
        /**
          * The base colour value (for dynamic generation). Default is 'var(--primary-colour)'.
          * @default 'var(--primary-colour)'
         */
        "colourValue"?: string;
    }
    interface FabSelect {
        /**
          * If multiple, how many options will be shown in the collapsed state before showing "+X more"
          * @default 2
         */
        "collapsedCount"?: number;
        /**
          * Whether the select is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Whether multiple options can be selected
          * @default false
         */
        "multiple"?: boolean;
        /**
          * The name of the form control (used for form submission)
          * @default ''
         */
        "name"?: string;
        /**
          * Emitted when selection changes
         */
        "onFabChange"?: (event: FabSelectCustomEvent<string | string[]>) => void;
        /**
          * Placeholder text to display when no option is selected
          * @default 'Select an option'
         */
        "placeholder"?: string;
        /**
          * Whether the select is required
          * @default false
         */
        "required"?: boolean;
    }
    interface FabSidebar {
    }
    interface FabSidebarContent {
    }
    interface FabSidebarFooter {
    }
    interface FabSidebarGroup {
        /**
          * Whether the group is currently collapsed.
          * @default true
         */
        "groupCollapsed"?: boolean;
        /**
          * Whether the group is collapsible.
          * @default false
         */
        "groupCollapsible"?: boolean;
        /**
          * Optional heading for the group.
         */
        "heading"?: string;
    }
    interface FabSidebarHeader {
    }
    interface FabSidebarItem {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "href"?: string;
        "icon"?: string;
        "label"?: string;
    }
    interface FabSitePalette {
        /**
          * The base colour value (for dynamic generation). Default is 'var(--primary-colour)'.
          * @default 'var(--primary-colour)'
         */
        "colourValue"?: string;
        /**
          * The colour harmony to display. Options are 'complementary', 'analogous', 'triadic', 'tetradic', 'split', and 'neutral'. Default is 'complementary'.
          * @default 'complementary'
         */
        "harmony"?: 'complementary' | 'analogous' | 'triadic' | 'tetradic' | 'split' | 'neutral';
        /**
          * @default true
         */
        "showHarmonies"?: boolean;
    }
    interface FabSkeuSwitch {
    }
    interface FabThemeSwitcher {
    }
    interface FabToggle {
        /**
          * Whether we show the indicator light
         */
        "showIndicator"?: boolean;
    }
    interface FabWcagPalette {
    }
    interface IntrinsicElements {
        "fab-button": FabButton;
        "fab-colour-palettes": FabColourPalettes;
        "fab-icon": FabIcon;
        "fab-option": FabOption;
        "fab-palette": FabPalette;
        "fab-select": FabSelect;
        "fab-sidebar": FabSidebar;
        "fab-sidebar-content": FabSidebarContent;
        "fab-sidebar-footer": FabSidebarFooter;
        "fab-sidebar-group": FabSidebarGroup;
        "fab-sidebar-header": FabSidebarHeader;
        "fab-sidebar-item": FabSidebarItem;
        "fab-site-palette": FabSitePalette;
        "fab-skeu-switch": FabSkeuSwitch;
        "fab-theme-switcher": FabThemeSwitcher;
        "fab-toggle": FabToggle;
        "fab-wcag-palette": FabWcagPalette;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fab-button": LocalJSX.FabButton & JSXBase.HTMLAttributes<HTMLFabButtonElement>;
            "fab-colour-palettes": LocalJSX.FabColourPalettes & JSXBase.HTMLAttributes<HTMLFabColourPalettesElement>;
            "fab-icon": LocalJSX.FabIcon & JSXBase.HTMLAttributes<HTMLFabIconElement>;
            "fab-option": LocalJSX.FabOption & JSXBase.HTMLAttributes<HTMLFabOptionElement>;
            "fab-palette": LocalJSX.FabPalette & JSXBase.HTMLAttributes<HTMLFabPaletteElement>;
            "fab-select": LocalJSX.FabSelect & JSXBase.HTMLAttributes<HTMLFabSelectElement>;
            "fab-sidebar": LocalJSX.FabSidebar & JSXBase.HTMLAttributes<HTMLFabSidebarElement>;
            "fab-sidebar-content": LocalJSX.FabSidebarContent & JSXBase.HTMLAttributes<HTMLFabSidebarContentElement>;
            "fab-sidebar-footer": LocalJSX.FabSidebarFooter & JSXBase.HTMLAttributes<HTMLFabSidebarFooterElement>;
            "fab-sidebar-group": LocalJSX.FabSidebarGroup & JSXBase.HTMLAttributes<HTMLFabSidebarGroupElement>;
            "fab-sidebar-header": LocalJSX.FabSidebarHeader & JSXBase.HTMLAttributes<HTMLFabSidebarHeaderElement>;
            "fab-sidebar-item": LocalJSX.FabSidebarItem & JSXBase.HTMLAttributes<HTMLFabSidebarItemElement>;
            "fab-site-palette": LocalJSX.FabSitePalette & JSXBase.HTMLAttributes<HTMLFabSitePaletteElement>;
            "fab-skeu-switch": LocalJSX.FabSkeuSwitch & JSXBase.HTMLAttributes<HTMLFabSkeuSwitchElement>;
            "fab-theme-switcher": LocalJSX.FabThemeSwitcher & JSXBase.HTMLAttributes<HTMLFabThemeSwitcherElement>;
            "fab-toggle": LocalJSX.FabToggle & JSXBase.HTMLAttributes<HTMLFabToggleElement>;
            "fab-wcag-palette": LocalJSX.FabWcagPalette & JSXBase.HTMLAttributes<HTMLFabWcagPaletteElement>;
        }
    }
}
